const SYNC_INTERVAL = 60_000;
const YOUTUBE_DOMAINS = ['.youtube.com', '.google.com'];

async function getServerUrl() {
  const { serverUrl } = await chrome.storage.sync.get('serverUrl');
  return serverUrl || '';
}

function formatNetscapeCookie(c) {
  const domain = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
  const flag = 'TRUE';
  const path = c.path || '/';
  const secure = c.secure ? 'TRUE' : 'FALSE';
  const expires = c.expirationDate ? Math.floor(c.expirationDate) : 0;
  return `${domain}\t${flag}\t${path}\t${secure}\t${expires}\t${c.name}\t${c.value}`;
}

async function syncCookies() {
  const serverUrl = await getServerUrl();
  if (!serverUrl) return;

  const allCookies = await chrome.cookies.getAll({ domain: 'youtube.com' });
  const googleCookies = await chrome.cookies.getAll({ domain: 'google.com' });
  const cookies = [...allCookies, ...googleCookies];

  if (!cookies.length) return;

  const lines = [
    '# Netscape HTTP Cookie File',
    '# Auto-generated by YT Cookie Sync',
    ''
  ];
  for (const c of cookies) {
    if (c.name && c.value) lines.push(formatNetscapeCookie(c));
  }

  try {
    await fetch(`${serverUrl}/api/cookies`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content: lines.join('\n') })
    });
    await chrome.storage.sync.set({ lastSync: Date.now() });
  } catch (e) {
    console.error('Cookie sync failed:', e);
  }
}

chrome.runtime.onInstalled.addListener(() => {
  syncCookies();
  chrome.alarms.create('cookieSync', { periodInMinutes: 1 });
});

chrome.alarms.onAlarm.addListener((alarm) => {
  if (alarm.name === 'cookieSync') syncCookies();
});

chrome.cookies.onChanged.addListener((change) => {
  if (change.removed) return;
  const c = change.cookie;
  if (YOUTUBE_DOMAINS.some(d => c.domain.endsWith(d.replace(/^\./, '')))) {
    syncCookies();
  }
});
